baseURL = "https://lambent-caramel-348a78.netlify.app/"
title = "GoBlog – Tech, Insights & Daily Discoverie"
theme = "PaperMod"
defaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "My Auto Blog"
  description = "Explore curated articles on technology, digital trends, and practical insights designed for modern readers."
  author = "Admenco"

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true


  # 🔥 penting: jangan pakai slash di depan
  [params.assets]
    favicon = "favicon.ico"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 3

  [[menu.main]]
    name = "Privacy"
    url = "privacy-policy/"
    weight = 4

  [[menu.main]]
    name = "DMCA"
    url = "dmca/"
    weight = 5

  [[menu.main]]
    name = "Sitemap"
    url = "sitemap.xml"
    weight = 6

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "daily"
  priority = 0.8
  filename = "sitemap.xml"

# 🔥 INI KUNCI UNTUK PAPERMOD + SUBFOLDER
relativeURLs = false
canonifyURLs = false